# Use root as password credentials
version: '3.1'

services:
  db:
    image: redis:7.2.0
    ports:
      - "6379:6379"
    restart: always 
    container_name: db_redis_7_2_0
    volumes:
      - ./redis_data:/usr/local/etc/redis

    environment:
      # ALLOW_EMPTY_PASSWORD=yes
      REDIS_PASSWORD: root