# Use root/root as user/password credentials
version: '3.1'

services:
  db:
    image: cassandra:4.1.3
    ports:
      - "9042:9042"
    restart: always 
    container_name: db_cassandra_4_1_3
    volumes:
      - ./cassandra_data:/var/lib/cassandra

    environment:
      CASSANDRA_USER: root
      CASSANDRA_PASSWORD: root
      CASSANDRA_CLUSTER_NAME: cloudinfra